export const BOOK_DEFINITIONS = [
  ["GEN", "Genesis", "gen ge gn"],
  ["EXO", "Exodus", "exod exo ex"],
  ["LEV", "Leviticus", "lev le lv"],
  ["NUM", "Numbers", "num nu nm nb"],
  ["DEU", "Deuteronomy", "deut deu dt"],
  ["JOS", "Joshua", "josh jos jsh"],
  ["JDG", "Judges", "judg jdg jdgs"],
  ["RUT", "Ruth", "ruth rut ru"],
  ["1SA", "1 Samuel", "1sam 1sa 1sm"],
  ["2SA", "2 Samuel", "2sam 2sa 2sm"],
  ["1KI", "1 Kings", "1kings 1kgs 1ki"],
  ["2KI", "2 Kings", "2kings 2kgs 2ki"],
  ["1CH", "1 Chronicles", "1chron 1chr 1ch"],
  ["2CH", "2 Chronicles", "2chron 2chr 2ch"],
  ["EZR", "Ezra", "ezr ezra"],
  ["NEH", "Nehemiah", "neh ne"],
  ["EST", "Esther", "esth est es"],
  ["JOB", "Job", "job jb"],
  ["PSA", "Psalms", "psalm psalms psa ps pslm pss"],
  ["PRO", "Proverbs", "prov pro pr prv"],
  ["ECC", "Ecclesiastes", "eccles eccl ecc ec qoheleth"],
  [
    "SNG",
    "Song of Solomon",
    "songofsolomon songofsongs song sos sng canticles",
  ],
  ["ISA", "Isaiah", "isa is"],
  ["JER", "Jeremiah", "jer je jr"],
  ["LAM", "Lamentations", "lam la"],
  ["EZK", "Ezekiel", "ezek ezk eze"],
  ["DAN", "Daniel", "dan da dn"],
  ["HOS", "Hosea", "hos ho"],
  ["JOL", "Joel", "joel jol jl"],
  ["AMO", "Amos", "amos amo am"],
  ["OBA", "Obadiah", "obad oba ob"],
  ["JON", "Jonah", "jonah jon jnh"],
  ["MIC", "Micah", "mic mi"],
  ["NAM", "Nahum", "nahum nah nam na"],
  ["HAB", "Habakkuk", "hab hb"],
  ["ZEP", "Zephaniah", "zeph zep zp"],
  ["HAG", "Haggai", "hag hg"],
  ["ZEC", "Zechariah", "zech zec zc"],
  ["MAL", "Malachi", "mal ml"],
  ["MAT", "Matthew", "matt mat mt"],
  ["MRK", "Mark", "mark mrk mk mr"],
  ["LUK", "Luke", "luke luk lk"],
  ["JHN", "John", "john jhn jn"],
  ["ACT", "Acts", "acts act ac"],
  ["ROM", "Romans", "rom ro rm"],
  ["1CO", "1 Corinthians", "1cor 1co"],
  ["2CO", "2 Corinthians", "2cor 2co"],
  ["GAL", "Galatians", "gal ga"],
  ["EPH", "Ephesians", "eph ep"],
  ["PHP", "Philippians", "phil php pp"],
  ["COL", "Colossians", "col co"],
  ["1TH", "1 Thessalonians", "1thess 1thes 1th"],
  ["2TH", "2 Thessalonians", "2thess 2thes 2th"],
  ["1TI", "1 Timothy", "1tim 1ti"],
  ["2TI", "2 Timothy", "2tim 2ti"],
  ["TIT", "Titus", "titus tit ti"],
  ["PHM", "Philemon", "philem phlm phm"],
  ["HEB", "Hebrews", "heb he"],
  ["JAS", "James", "james jas jam jm"],
  ["1PE", "1 Peter", "1pet 1pe 1pt"],
  ["2PE", "2 Peter", "2pet 2pe 2pt"],
  ["1JN", "1 John", "1john 1jn 1jhn"],
  ["2JN", "2 John", "2john 2jn 2jhn"],
  ["3JN", "3 John", "3john 3jn 3jhn"],
  ["JUD", "Jude", "jude jud jd"],
  ["REV", "Revelation", "revelation revelations rev re rv"],
] as const;
